# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(848, 618)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.connect = QtWidgets.QPushButton(parent=self.centralwidget)
        self.connect.setObjectName("connect")
        self.verticalLayout_2.addWidget(self.connect)
        spacerItem = QtWidgets.QSpacerItem(833, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.sendGcode = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sendGcode.setObjectName("sendGcode")
        self.verticalLayout_2.addWidget(self.sendGcode)
        spacerItem1 = QtWidgets.QSpacerItem(833, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 848, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(parent=self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuEdit = QtWidgets.QMenu(parent=self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuFilter = QtWidgets.QMenu(parent=self.menubar)
        self.menuFilter.setObjectName("menuFilter")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionUpload_Image = QtGui.QAction(parent=MainWindow)
        self.actionUpload_Image.setObjectName("actionUpload_Image")
        self.actionUpload_Gcode = QtGui.QAction(parent=MainWindow)
        self.actionUpload_Gcode.setObjectName("actionUpload_Gcode")
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionUpload_Image)
        self.menuMenu.addAction(self.actionUpload_Gcode)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuFilter.menuAction())

        # ADDING NEW BUTTON FOR POP UP WINDOW
        self.colorButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.colorButton.clicked.connect(self.open_color_window) # add to open pop up window
        self.colorButton.setObjectName("Color")
        self.verticalLayout_2.addWidget(self.colorButton)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connect.setText(_translate("MainWindow", "Connect to Arduino"))
        self.sendGcode.setText(_translate("MainWindow", "Start Drawing"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuFilter.setTitle(_translate("MainWindow", "Filter"))
        self.actionUpload_Image.setText(_translate("MainWindow", "Upload Image"))
        self.actionUpload_Gcode.setText(_translate("MainWindow", "Upload Gcode"))

        # ADDED COLOR BUTTON
        self.colorButton.setText(_translate("MainWindow", "Color"))

